<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\app-icon.ico</ApplicationIcon>
    <Version>1.4.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app-icon.ico"/>
    <Resource Include="Fonts\*.ttf"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="BijouHub.Core\BijouHub.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BijouHub.Core\**" />
    <Compile Remove="BijouHub.Mac\**" />
    <EmbeddedResource Remove="BijouHub.Core\**" />
    <EmbeddedResource Remove="BijouHub.Mac\**" />
    <None Remove="BijouHub.Core\**" />
    <None Remove="BijouHub.Mac\**" />
  </ItemGroup>

</Project>
