namespace BijouHub.Services;

public static class Greetings
{
    private static readonly Random Rng = new();

    public static readonly string[] Messages =
    {
        "Let's build something great today.",
        "Back at it. Let's go.",
        "Today's the day you ship it.",
        "You showed up. That's the hard part.",
        "One session at a time.",
        "Let's make some progress.",
        "Ready when you are.",
        "Time to get in the zone.",
        "Small steps, real progress.",
        "You've got this.",
        "Let's turn the ideas into something real.",
        "Another day, another chance to create.",
        "Focus mode: activated.",
        "Let's see what you can knock out today.",
        "The next upload starts right here.",
        "Momentum starts with one click.",
        "Every edit brings you closer.",
        "Let's chip away at it.",
        "Good to see you back.",
        "Let's make today count.",
        "Time to build.",
        "Consistency beats intensity. Let's go.",
        "Show up, do the work, repeat.",
        "You're closer than you think.",
        "Let's turn this into a good one.",
        "Deep breath. Let's create.",
        "First step: open BijouHub. Done. Now the rest.",
        "The channel doesn't grow itself. Let's go.",
        "Today's a good day to finish something.",
        "Let's stack another win.",
        "Progress over perfection.",
        "Get in, get focused, get it done.",
        "The grind pays off. Keep going.",
        "Let's make future-you proud.",
        "One task at a time. Let's start.",
        "Ready to make something people watch?",
        "This session counts. Let's use it well.",
        "You already made the hardest decision — showing up.",
        "Let's get some real work done.",
        "The next great video starts with this click.",
        "Let's turn 'someday' into 'today'.",
        "Big things start small. Let's start.",
        "Editing bay's open. Let's go.",
        "Let's put in the reps.",
        "The algorithm rewards consistency — let's feed it.",
        "Nothing gets done by waiting. Let's move.",
        "Let's carve out something good today.",
        "You know the drill. Let's roll.",
        "Time to turn footage into a story.",
        "Let's make it click-worthy.",
        "This is your studio. Let's use it.",
        "Every great channel started with one boring Tuesday.",
        "Let's knock something off the list.",
        "You don't have to feel ready. Just start.",
        "Let's see what today's session brings.",
        "Keep the streak alive.",
        "Let's put a dent in the to-do list.",
        "Focus time. Let's make it count.",
        "The thumbnail isn't going to make itself.",
        "Let's find that next hook.",
        "Slow progress beats no progress.",
        "You're allowed to make it messy first.",
        "Let's get something in the export folder today.",
        "Discipline now, highlight reel later.",
        "Let's chase that next milestone.",
        "Today's session: let's make it a good one.",
        "Get comfortable. This might take a minute — that's fine.",
        "Let's turn raw footage into something worth watching.",
        "Every video is just a bunch of small decisions. Let's make some.",
        "Let's give today's idea a real shot.",
        "You're one session away from momentum.",
        "Let's make the boring parts fast so the fun parts shine.",
        "Time to build the thing only you can build.",
        "Let's get ahead of deadline-you.",
        "The best time to start was earlier. The next best time is now.",
        "Let's put something great into the world.",
        "Your audience is waiting. Let's not keep them too long.",
        "Let's turn today into content.",
        "Let's make some noise.",
        "Here's to another productive session.",
        "Let's get lost in the work for a bit.",
        "Today's goal: make tomorrow easier.",
        "Let's earn that render bar filling up.",
        "Cut the scroll, start the scroll bar. Let's edit.",
        "Let's give this project the attention it deserves.",
        "You've done harder things than this. Let's go.",
        "Let's build the thing you'll be glad you started.",
        "New session, new progress.",
        "Let's put in a focused hour.",
        "Let's stop thinking about it and start doing it.",
        "Time to trade scrolling for creating.",
        "Let's see this project through a little further.",
        "Every pro was once mid-edit at an awkward hour. Let's join them.",
        "Let's make the next ten minutes count.",
        "You're the only one who can finish this. Let's go.",
        "Let's get this idea out of your head and onto the timeline.",
        "Consistency is the whole game. Let's play it.",
        "Let's give today's project some love.",
        "Ready, set, create.",
        "Let's not let this idea go cold.",
        "Today's a good day to be productive.",
        "Let's earn the coffee break.",
        "Let's make some real headway.",
        "The next viewer's favorite video might be the one you make today.",
        "Let's get the ball rolling.",
        "Let's put today to good use.",
        "You picked this project for a reason. Let's honor that.",
        "Let's start strong.",
        "Let's finish what you started.",
        "Time to turn intention into output.",
        "Let's make good use of this focus window.",
        "Let's move the needle today.",
        "You're not behind. You're right on time. Let's go.",
        "Let's give it your full attention for a bit.",
        "Let's build the highlight reel of your week.",
        "Time to make the thing you've been thinking about.",
        "Let's get one step closer to done.",
        "This is your reminder that starting is the hardest part — and you just did.",
        "Let's turn effort into output.",
        "Let's make today's session the good kind of productive.",
        "Let's put a checkmark on something today.",
        "Alright, let's see what we're working with.",
        "Let's get after it.",
        "Let's build the thing worth watching.",
        "Let's make it worth the upload.",
        "Time to get your hands dirty with the edit.",
        "Let's give the project a good push forward.",
        "Let's make progress you can actually see.",
        "The timeline's waiting. Let's fill it.",
        "Let's get into flow state.",
        "Today's a good day to be a little unstoppable.",
        "Let's make it happen.",
        "New session. Fresh energy. Let's go.",
        "Let's do the thing.",
        "Let's put this idea to work.",
        "Let's make good on that plan.",
        "You showed up — the rest is just execution.",
        "Let's give this the focus it deserves.",
        "Let's turn today into a good chapter of the story.",
        "Momentum's a myth until you start. Let's start.",
        "Let's build toward the next upload.",
        "Let's get comfortable being productive.",
        "Let's put today's energy somewhere good.",
        "Time to make the edit better than the plan.",
        "Let's push this project forward, even a little.",
        "Let's make it count, however long you've got.",
        "This is the part where you actually do it. Let's go."
    };

    public static string Random() => Messages[Rng.Next(Messages.Length)];
}
